artifacts_root: artifacts 

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://example.com/data.csv"
  local_data_file: "data.csv"
  unzip_dir: "artifacts/data_ingestion"

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/dataset
  tokenizer_name: google/tokenizer_name

model_trainer:
  root_dir: artifacts/model_trainer
  data_path: artifacts/data_transformation/transformed_data
  model_ckpt: artifacts/model_trainer/model